language: node_js
node_js:
  - "8"
before_install:
  - "if [[ `npm -v` != 6* ]]; then npm i -g npm@6; fi"
  - npm --version
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
script:
  - npm run check
after_success:
  - "cat coverage/lcov.info | coveralls --verbose"
cache:
  directories:
  - $HOME/.npm
  - node_modules
addons:
  firefox: "latest"
